### ISSUE TITLE
[Code refactoring] Destructuring package & file requests?

### ISSUE THREAD

**Issue by DevCassie** [GAndersenCode/TicketBot-v1.0#1]
In the image down below (index.js), the entire discord.js package is called, when only Collection and Client classes are used. 
![image](https://user-images.githubusercontent.com/19227530/109818215-0987c080-7c33-11eb-8533-e1e5a1347bd5.png)

Code refactor would look something like this:
```JavaScript
const { Client, Collection } = require('discord.js');
const client = new Client({ partials: ['MESSAGE', 'REACTION'] });
client.commands = new Collection();
```

**Comment by LetUsRepair** [comment]
Apologies for taking time to answer, I'm still figuring the actual workings of GitHub out...
I used destructuring in other files, but for some reason I didn't do it consistently.
All code files are updated to use destructuring and pushed to main branch!

@DevCassie Thanks for the heads up!

**Comment by DevCassie** [comment]
> Apologies for taking time to answer, I'm still figuring the actual workings of GitHub out...
> I used destructuring in other files, but for some reason I didn't do it consistently.
> All code files are updated to use destructuring and pushed to main branch!
> 
> @DevCassie Thanks for the heads up!

No problem @GAndersenCode ! Any interesting thing you wish to add in the future? Perhaps I could contribute later?

**Comment by LetUsRepair** [comment]
I was thinking about adding database support (it would be MySQL, as that is my preference) to keep track of tickets and first welcome message of ticket. That way it could be written so that when reacting with the ❌ only closes the ticket if the reaction was added to the welcome message of the support ticket, and it was the tickets user that reacted to close...

**Comment by DevCassie** [comment]
> I was thinking about adding database support (it would be MySQL, as that is my preference) to keep track of tickets and the first welcome message of a ticket. That way it could be written so that when reacting with the ❌ only closes the ticket if the reaction was added to the welcome message of the support ticket, and it was the ticket user that reacted to close...

Sounds interesting and promising. I've read something about a transcript command. But what about commands like adding members, removing members to a ticket? Not sure if that's anything interesting.

**Comment by LetUsRepair** [comment]
I found Ansons transcript command a short while ago and got it running on v12.
I was thinking of of adding that functionality to the end of a ticket channel, so admins can save an HTML transcript of the ticket info (if they want to).
Adding and removing members I'm not sure about, as the ticket is meant to be private between guild owner and user. The permissions are overwritten though, to remove the user when he/she reacts to the first message.
